# This acts as a means of calling user functions while handling errors and formatting things for the API.
# The code here was in part generated by an AI language model and then modified.
# Author: Seth Tedder
# Models used: ChatGPT-5, VS copilot

from flask import jsonify

import user_functions

def validate_user_json(data: dict):
    required = ["username"]
    for field in required:
        if field not in data:
            return f"Missing field: {field}"
    return None

def get_all_users():
    users = user_functions.fetch_all_users()
    return jsonify(users), 200

def get_user(user_id):
    user = user_functions.fetch_user_by_id(user_id)
    if not user:
        return jsonify({"error": "User not found"}), 404
    return jsonify(user), 200

def create_user(data):
    error = validate_user_json(data)
    if error:
        return jsonify({"error": error}), 400

    new_id = user_functions.insert_user(data)
    return jsonify({"message": "User created", "id": new_id}), 201

def update_user(user_id, data):
    user = user_functions.fetch_user_by_id(user_id)
    if not user:
        return jsonify({"error": "User not found"}), 404

    user_functions.update_user(user_id, data)
    return jsonify({"message": "User updated"}), 200

def delete_user(user_id):
    user = user_functions.fetch_user_by_id(user_id)
    if not user:
        return jsonify({"error": "User not found"}), 404

    user_functions.delete_user(user_id)
    return jsonify({"message": "User deleted"}), 200
