# This is the route for the user entity API.
# The code here was in part generated by an AI language model and then modified.
# Author: Seth Tedder
# Models used: ChatGPT-5, VS copilot

from flask import Blueprint, request
import user_controller as Controller

user_bp = Blueprint('user_bp', __name__)

@user_bp.get("/users")
def get_all_users():
    return Controller.get_all_users()

@user_bp.get("/users/<int:user_id>")
def get_user(user_id):
    return Controller.get_user(user_id)

@user_bp.post("/users")
def create_user():
    data = request.json
    return Controller.create_user(data)

@user_bp.put("/users/<int:user_id>")
def update_user(user_id):
    data = request.json
    return Controller.update_user(user_id, data)

@user_bp.delete("/users/<int:user_id>")
def delete_user(user_id):
    return Controller.delete_user(user_id)
